version: '3.3'

services:
  db:
#    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      TZ: Asia/Seoul
    ports:
      - 3306:3306

    container_name: mysql