### 로그인 페이지
GET http://localhost:9000/login

### 로그인
POST http://localhost:9000/login
Content-Type: application/x-www-form-urlencoded

memberId=admin1234&password=admin1234

### 로그인
POST http://localhost:9000/login
Content-Type: application/x-www-form-urlencoded

memberId=user1231234&password=123456

### 로그아웃
GET http://localhost:9000/logout