### 회원가입
POST http://localhost:9000/member
Content-Type: application/json

{
  "member": {
    "memberId": "user1234",
    "password": "12341234"
  },
  "roles": ["USER"],
  "memberInfo": {
    "name": "미도레",
    "email": "doremi@doremi-market.com",
    "phoneNumber": "01012341234",
    "postNo": "1234",
    "roadAddress": "서울특별시 영등포구 여의대로 108",
    "detailAddress": "더현대",
    "gender": "FEMALE",
    "birthday": "1990-03-26"
  }
}

### 회원가입
POST http://localhost:9000/member
Content-Type: application/json

{
  "member": {
    "memberId": "admintest",
    "password": "admin1234"
  },
  "roles": ["ADMIN", "USER"],
  "memberInfo": {
    "name": "관리자",
    "email": "doremi@doremi-market.com",
    "phoneNumber": "01012341234",
    "postNo": "1234",
    "roadAddress": "서울특별시 영등포구 여의대로 108",
    "detailAddress": "더현대",
    "gender": "UNCHECKED",
    "birthday": "1990-03-26"
  }
}

### 회원가입
POST http://localhost:9000/api/v1/member
Content-Type: application/json

< ./signup.json

### 회원가입
POST http://localhost:9000/api/v1/member
Content-Type: application/json

< ./signup.json