### 회원가입
POST http://localhost:9000/member
Content-Type: application/json

{
  "member": {
    "memberId": "user1234",
    "password": "12341234"
  },
  "roles": ["USER"],
  "memberInfo": {
    "name": "미도레",
    "email": "doremi@doremi-market.com",
    "phoneNumber": "01012341234",
    "address": "서울특별시 영등포구 여의대로 108",
    "gender": "female",
    "birthday": "1990-03-26"
  }
}

### 회원가입
POST http://localhost:9000/member
Content-Type: application/json

{
  "member": {
    "memberId": "admin1",
    "password": "1234"
  },
  "roles": ["ADMIN", "USER"],
  "memberInfo": {
    "name": "관리자",
    "email": "doremi@doremi-market.com",
    "phoneNumber": "01012341234",
    "address": "서울특별시 영등포구 여의대로 108",
    "sex": "NONE",
    "birthday": "1990-03-26"
  }
}

### 회원가입
POST http://localhost:9000/api/v1/member
Content-Type: application/json

< ./signup.json

### 로그인
GET http://localhost:9000/login
Content-Type: application/json

{
  "memberId": "user1231234",
  "password": "123456"
}

### 회원가입
POST http://localhost:9000/api/v1/member
Content-Type: application/json

< ./signup.json

### 로그인
GET http://localhost:9000/login
Content-Type: application/json

{
  "memberId": "user1231234",
  "password": "123456"
}