server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doremi?autoReconnect=true&useUnicode=true&serverTimezone=UTC
    username: root
    password: password

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: on
